-- Site-wide brand copy (editable in Admin → Site content)
insert into public.site_content (key, value) values
('business_contact', '{"phone":"+1 246 000 0000","phone_href":"tel:+12460000000","email":"hello@mistatravel.com","whatsapp_href":"https://wa.me/12460000000","whatsapp_label":"Message us anytime","whatsapp_short_label":"WhatsApp us","whatsapp_footer_label":"WhatsApp: Message us","office":"Hastings Main Road, Christ Church, Barbados","address_line1":"Hastings Main Road, Christ Church","address_line2":"Barbados, Caribbean","map_label":"Hastings, Christ Church · Barbados","hours":"Mon–Fri · 8:00 AM – 7:00 PM\nSaturday · 9:00 AM – 4:00 PM\nSunday · By appointment"}'),
('social_links', '[{"label":"Instagram","icon":"instagram","href":"#"},{"label":"Facebook","icon":"facebook","href":"#"},{"label":"TripAdvisor","icon":"map-pin","href":"#"}]'),
('footer', '{"tagline":"Bespoke luxury journeys across the Caribbean — from the Pitons of St. Lucia to the cays of the Bahamas, crafted by islanders who know every hidden cove.","copyright":"© 2026 Mista Concierge Travel. All rights reserved.","terms_label":"Terms","terms_href":"#","privacy_label":"Privacy","privacy_href":"#","sitemap_label":"Sitemap","sitemap_href":"#"}'),
('contact_page', '{"eyebrow":"Contact Us","headline":"Let''s plan your escape","description":"Tell us your dream and our concierge team will design it. We respond within 24 hours.","info_heading":"Get in touch","hours_heading":"Hours of operation"}'),
('about_page', '{"hero_eyebrow":"About Us","hero_headline":"Your gateway to unforgettable Caribbean experiences","hero_description":"We don''t sell trips. We craft the journeys you''ll talk about for the rest of your life.","story_eyebrow":"Our Story","story_headline":"Born on the islands, built for travelers","story_p1":"Mista Concierge Travel began in 2014 with a simple belief: the Caribbean deserves to be experienced, not just visited. Founder Marcus \"Mista\" Alleyne grew up sailing between the islands, and watched too many visitors leave having seen only a resort wall.","story_p2":"Today our team of islanders crafts bespoke journeys across fifteen destinations — opening doors to private chefs, hidden coves and family-run estates that no booking site can reach. Every itinerary is one of one.","values_eyebrow":"What We Stand For","values_headline":"Our core values","team_eyebrow":"The People","team_headline":"Meet our team","certs_label":"Trusted & Recognized"}'),
('destinations_page', '{"hero_eyebrow":"Where We Go","hero_headline":"Discover the Caribbean''s finest islands","hero_description":"Six signature destinations, each with its own rhythm. Find the one that calls to you — then let us craft the journey around it.","grid_headline":"Every island, beautifully covered","cta_headline":"Can''t decide? Let us help.","cta_description":"Tell us how you like to travel and our concierge team will match you to the perfect island and itinerary.","cta_label":"Plan My Journey","cta_href":"/contact"}'),
('tours_page', '{"eyebrow":"Tours & Experiences","headline":"All Tours & Experiences","description":"Handcrafted journeys across the Caribbean''s most beautiful islands. Filter to find the escape that fits you."}'),
('home_featured_tours', '{"eyebrow":"Curated Experiences","headline":"Featured Tours","description":"Our most-loved journeys, each one a seamless blend of wild adventure and quiet luxury.","cta_label":"View All Tours","cta_href":"/tours"}'),
('home_why_choose', '{"eyebrow":"The Mista Difference","headline":"Why Choose Mista Concierge"}'),
('home_destinations', '{"eyebrow":"Where We Go","headline":"Discover the islands","link_label":"All destinations →","link_href":"/destinations"}'),
('home_testimonials', '{"eyebrow":"Traveler Stories","headline":"Loved by adventurers worldwide"}')
on conflict (key) do nothing;
